#!/usr/bin/env bash
# GENERATED by configure.sh for machine 'NCBCI-server' on 2026-06-08 — tracked, committed layout.
# Consumed by ./provision.sh via LAYOUT=. Regenerate any time with ./configure.sh.
# Contains NO secrets (the LUKS passphrase is entered interactively at provision time).
# shellcheck disable=SC2034

DISK="/dev/nvme0n1"
OS_TAG="${OS_TAG:-main_ubt26}"

ESP_SIZE="1GiB"
BOOT_SIZE="1GiB"

LUKS_NAME="${LUKS_NAME:-cryptroot}"

DEFAULT_BTRFS_OPTS="noatime,compress=zstd:1,discard=async,space_cache=v2"

SUBVOLS=(
  "@${OS_TAG}|/|${DEFAULT_BTRFS_OPTS}|recreate"
  "@${OS_TAG}_home|/home|${DEFAULT_BTRFS_OPTS}|recreate"
  "@${OS_TAG}_log|/var/log|${DEFAULT_BTRFS_OPTS}|recreate"
  "@${OS_TAG}_snapshots|/.snapshots|${DEFAULT_BTRFS_OPTS}|recreate"
  "@space|/space|${DEFAULT_BTRFS_OPTS}|preserve"
  "@archives|/archives|noatime,compress=zstd:5,discard=async,space_cache=v2|preserve"
)
